### ISSUE TITLE
Chromium 126.x - Error STATUS_DLL_INIT_FAILED

### ISSUE THREAD

**Issue by Uber-1** [ca-x/vivaldi_plus#49]
The Chromium dev builds ( https://download-chromium.appspot.com/dl/Win ; https://download-chromium.appspot.com/dl/Win_x64 ) don't work with "version.dll". Error **STATUS_DLL_INIT_FAILED**

Screenshot: 
![2](https://github.com/Bush2021/chrome_plus/assets/148308766/2951e6cf-0b44-4ec8-8ebc-8ce6f055fb35)

Another version.dll by Bush2021 is also affected.

**Comment by czyt** [comment]
thanks for the info.but i am not good at cpp,I will keep this issue open util updated to 126.x . @Uber-1

**Comment by Uber-1** [comment]
v1.5.8.1 works fine.
Thanks!
![clipboard](https://github.com/ca-x/vivaldi_plus/assets/148308766/9431aa4c-e0db-4bee-a180-79ae3878db50)
